import express, { Router } from 'express';
import {
  createEmployeeOnboardingAPIHandler,
  getEmployeeListAPIHandler,
  getAutoGeneratedEmpIdAPIHandler,
  saveEmployeeDocumentAPIHandler,
  getEmployeeDocumentsAPIHandler,
  saveEmployeeCompensationAPIHandler,
  getEmployeeCompensationAPIHandler,
  getEmployeeDetailsAPIHandler
} from './onboarding.controller';
import { accessTokenValidatorMiddleware } from '../../common/middleware/error.middleware';
import { upload } from '../../common/middleware/upload.middleware';

const ONBOARDING_ROUTER: Router = express.Router();

//#region Employee Details
ONBOARDING_ROUTER.get(
  "/auto_generated_emp_id",
  accessTokenValidatorMiddleware,
  getAutoGeneratedEmpIdAPIHandler
)

// ==================== CREATE/UPDATE EMPLOYEE ====================
ONBOARDING_ROUTER.post(
  "/employee-onboarding",
  accessTokenValidatorMiddleware,
  upload.single("profileImage"),
  createEmployeeOnboardingAPIHandler
);

//  ==================== GET EMPLOYEE ====================
ONBOARDING_ROUTER.post(
  "/employee-list-pagination",
  accessTokenValidatorMiddleware,
  getEmployeeListAPIHandler
);

ONBOARDING_ROUTER.post(
  "/employee-details",
  accessTokenValidatorMiddleware,
  getEmployeeDetailsAPIHandler
);
//#region 

//#region Employee Documents
// ==================== DOCUMENT UPLOAD EMPLOYEE ====================
ONBOARDING_ROUTER.post(
  "/upload-document",
  accessTokenValidatorMiddleware,
  upload.single("file"),
  saveEmployeeDocumentAPIHandler
);

// ==================== DOCUMENTS GET EMPLOYEE ====================
ONBOARDING_ROUTER.post(
  "/get-document",
  accessTokenValidatorMiddleware,
  getEmployeeDocumentsAPIHandler
);

//#region Employee Compensiation
// Save Compensiation
ONBOARDING_ROUTER.post(
  "/save-compensation",
  accessTokenValidatorMiddleware,
  saveEmployeeCompensationAPIHandler
);

// Get Compensiation
ONBOARDING_ROUTER.get(
  "/get-compensation/:employee_uuid",
  accessTokenValidatorMiddleware,
  getEmployeeCompensationAPIHandler
);




export { ONBOARDING_ROUTER };
