import { CommonModule, Location } from '@angular/common';
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { Subject, takeUntil } from 'rxjs';
import { API_ENDPOINTS } from '../../../../core/config/api-endpoints';
import { ApiClient } from '../../../../core/services/api-client.service';
import { CommonService } from '../../../../core/services/common.service';
import { PageHeader } from '../../../../shared/components/page-header/page-header';
import { MATERIAL } from '../../../../shared/material/materials';
import { Compensation } from '../compensation/compensation';
import { DocumentCollection } from '../document-collection/document-collection';
import { environment } from '../../../../../environments/environement';

@Component({
  selector: 'app-employee-onboarding',
  imports: [MATERIAL, FormsModule, CommonModule, ReactiveFormsModule, RouterModule, DocumentCollection, Compensation, PageHeader],
  templateUrl: './employee-onboarding.html',
  styleUrl: './employee-onboarding.scss',
})
export class EmployeeOnboarding implements OnInit {
  private _formBuilder = inject(FormBuilder);
  private _commonService = inject(CommonService);
  private _httpClient = inject(ApiClient);
  private _route = inject(ActivatedRoute);
  private _location = inject(Location);
  private _toastr = inject(ToastrService);
  // Page header tabs 

  currentTab: string | number | null = null;
  // Enum Options based on your Schema
  // Dynamic Lookup Options
  roles = signal<any[]>([]);
  maritalStatuses = ['SINGLE', 'MARRIED'];
  activeTab = signal<number>(0);
  genderList = signal<any[]>([]);
  employmentTypeList = signal<any[]>([]);
  workModeList = signal<any[]>([]);
  statusList = signal<any[]>([]);
  departmentList = signal<any[]>([]);
  designationList = signal<any[]>([]);
  employeesList = signal<any[]>([]);
  emergencyRelationList = signal<any[]>([]);
  probationStatusList = signal<any[]>([]);
  // Main Form Group
  // --- INDIVIDUAL FORM GROUPS ---
  personalDetails: FormGroup = this._formBuilder.group({
    profileImage: [null],
    firstName: ['', Validators.required],
    lastName: ['', Validators.required],
    email: ['', [Validators.email]],
    phone: ['', [Validators.required, Validators.pattern('^[0-9]{10}$')]],
    dob: [null],
    gender: ['male', Validators.required],
    address: [''],
    maritalStatus: [''],
    nationality: [''],
    password: ['', [Validators.minLength(6)]],
  });

  jobDetails: FormGroup = this._formBuilder.group({
    designation_id: ['', Validators.required],
    department_id: ['', Validators.required],
    joiningDate: [new Date(), Validators.required],
    workEmail: ['', [Validators.required, Validators.email]],
    reported_to: [''],
    work_location: [''],
    workMode: [''],
    role_id: [''],
    probationStartDate: [null],
    probationEndDate: [null],
    probationStatus: [''],
    probationNotes: [''],
    employee_id: ['', Validators.required],
    employmentType: [''],
    shift: ['']
  });

  emergencyContactDetails: FormGroup = this._formBuilder.group({
    contactName: [''],
    relation: [''],
    phone: ['']
  });


  destroy$ = new Subject<void>();
  previewUrl = signal<string | null>(null);
  id!: string;

  pageTabs: any[] = []
  shiftList: any = signal<any[]>([]);

  async ngOnInit(): Promise<void> {
    this.pageTabs = await this._commonService.getTabs('EMPLOYEE_ONBOARDING')
    // Set the first tab as active by default
    if (this.pageTabs.length > 0) {
      this.currentTab = this.pageTabs[0].key
    }
    this.id = this._route.snapshot.paramMap.get('id')!;
    this.loadLookupData();
    this.loadDepartments();
    this.loadEmployees();
    this.loadRoles();
    this.loadShifts();
    this.getAutoGeneratedId();
    if (this.id) {
      this.getEmployeeDetails();
    }
    // this.bindDummyData();
    // this.loadDesignations();
  }

  bindDummyData() {
    if (dummydata.personal_details) {
      this.personalDetails.patchValue({
        ...dummydata.personal_details,
        dob: dummydata.personal_details.dob ? new Date(dummydata.personal_details.dob) : null
      });
    }

    if (dummydata.job_details) {
      this.jobDetails.patchValue({
        ...dummydata.job_details,
        joiningDate: dummydata.job_details.joiningDate ? new Date(dummydata.job_details.joiningDate) : null,
        probationStartDate: dummydata.job_details.probationStartDate ? new Date(dummydata.job_details.probationStartDate) : null,
        probationEndDate: dummydata.job_details.probationEndDate ? new Date(dummydata.job_details.probationEndDate) : null,
      });
    }

    if (dummydata.emergency_contact) {
      this.emergencyContactDetails.patchValue({
        ...dummydata.emergency_contact
      });
    }
  }


  // --- LOGIC: File Upload ---
  onFileSelected(event: Event) {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (file) {
      this.personalDetails.get('profileImage')?.setValue(file);
      const reader = new FileReader();
      reader.onload = () => this.previewUrl.set(reader.result as string);
      reader.readAsDataURL(file);
    }
  }

  // ===== API CALL TO LOAD LOOKUP DATA =====
  async loadLookupData() {
    const categories = API_ENDPOINTS.lookup.categories;
    const lookupData = await this._commonService.getBulkLookupData([
      categories.gender,
      categories.employee_type,
      categories.work_mode,
      categories.status,
      categories.emergency_relation,
      categories.probation_status
    ]);

    if (lookupData) {
      this.genderList.set(lookupData[categories.gender] || []);
      this.employmentTypeList.set(lookupData[categories.employee_type] || []);
      this.workModeList.set(lookupData[categories.work_mode] || []);
      this.statusList.set(lookupData[categories.status] || []);
      this.emergencyRelationList.set(lookupData[categories.emergency_relation] || []);
      this.probationStatusList.set(lookupData[categories.probation_status] || []);
    }
  }

  // ===== API CALL TO LOAD DEPARTMENTS =====
  loadDepartments() {
    this._httpClient.get(API_ENDPOINTS.dropdown.departments).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        if (_res?.data && Array.isArray(_res.data)) {
          this.departmentList.set(_res.data);
        }
      },
      error: (_err: any) => {
        console.error('Error loading departments:', _err);
      }
    });
  }

  // ===== API CALL TO LOAD DESIGNATIONS =====
  loadDesignations(deptId: string) {
    const payload = {
      departmentId: deptId
    }
    this._httpClient.post(API_ENDPOINTS.dropdown.designations, payload).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        if (_res?.data && Array.isArray(_res.data)) {
          this.designationList.set(_res.data);
        }
      },
      error: (_err: any) => {
        console.error('Error loading designations:', _err);
      }
    });
  }

  // ===== API CALL TO LOAD ROLES =====
  loadRoles() {
    this._httpClient.get(API_ENDPOINTS.dropdown.roles).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        if (_res?.sts === 200 && Array.isArray(_res.data)) {
          this.roles.set(_res.data);
        }
      },
      error: (_err: any) => {
        console.error('Error loading roles:', _err);
      }
    });
  }

  // ===== API CALL TO LOAD EMPLOYEES =====
  loadEmployees() {
    this._httpClient.get(API_ENDPOINTS.dropdown.employees).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        if (_res?.sts === 200 && Array.isArray(_res.data)) {
          this.employeesList.set(_res.data);
        }
      },
      error: (_err: any) => {
        console.error('Error loading employees:', _err);
      }
    });
  }

  // ===== API CALL TO LOAD SHIFTS =====
  loadShifts() {
    this._httpClient.get(API_ENDPOINTS.dropdown.shifts).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        if (_res?.sts === 200 && Array.isArray(_res.data)) {
          this.shiftList.set(_res.data);
        }
      },
      error: (_err: any) => {
        console.error('Error loading shifts:', _err);
      }
    });
  }

  constructEmployeePayload() {
    const personal = this.personalDetails.value;
    const job = this.jobDetails.value;
    const emergency = this.emergencyContactDetails.value;

    // Helper to format date to YYYY-MM-DD
    const formatDate = (date: any) => {
      if (!date) return null;
      const d = new Date(date);
      return !isNaN(d.getTime()) ? d.toISOString().split('T')[0] : null;
    };

    // Constructing the specific JSON structure for API
    const apiPayload: any = {
      "personal_details": {
        "firstName": personal?.firstName || null,
        "lastName": personal?.lastName || null,
        "email": personal?.email || null,
        "phone": personal?.phone || null,
        "dob": formatDate(personal?.dob),
        "gender": personal?.gender || null,
        "address": personal?.address || null,
        "maritalStatus": personal?.maritalStatus || null,
        "nationality": personal?.nationality || null,
      },

      "job_details": {
        "designation_id": job?.designation_id || null,
        "department_id": job?.department_id || null,
        "joiningDate": job?.joiningDate ? formatDate(job?.joiningDate) : null,
        "workEmail": job?.workEmail || null,
        "reported_to": job?.reported_to || null,
        "work_location": job?.work_location || null,
        "workMode": job?.workMode || null,
        "role_id": job?.role_id || null,
        "probationStartDate": job?.probationStartDate ? formatDate(job?.probationStartDate) : null,
        "probationEndDate": job?.probationEndDate ? formatDate(job?.probationEndDate) : null,
        "probationStatus": job?.probationStatus || null,
        "probationNotes": job?.probationNotes || null,
        "employee_id": job?.employee_id || null,
        "employmentType": job?.employmentType || null,
        "shift_id": job?.shift || null
      },

      "emergency_contact": {
        "contactName": emergency?.contactName || null,
        "relation": emergency?.relation || null,
        "phone": emergency?.phone || null
      },
    };
    apiPayload.personal_details.password = personal?.password || null;
    let formData = new FormData();
    formData.append('personal_details', JSON.stringify(apiPayload.personal_details));
    formData.append('job_details', JSON.stringify(apiPayload.job_details));
    formData.append('emergency_contact', JSON.stringify(apiPayload.emergency_contact));
    formData.append('profileImage', this.personalDetails.get('profileImage')?.value);
    if (this.id) {
      formData.append('employee_uuid', this.id);
    }
    console.log('Constructed API Payload:', JSON.stringify(apiPayload, null, 2));
    alert('Payload generated! Check Console.');
    return formData;
  }

  onSubmit() {
    const payload = this.constructEmployeePayload();
    this._httpClient.post(API_ENDPOINTS.employee.create, payload).subscribe({
      next: (res) => {
        console.log('Onboarding Success:', res);
        this._toastr.success('Employee onboarded successfully!');
      },
      error: (err) => {
        console.error('Onboarding Error:', err);
      }
    })
  }



  getAutoGeneratedId() {
    this._httpClient.get(API_ENDPOINTS.employee.auto_generated_emp_id).pipe(takeUntil(this.destroy$)).subscribe({
      next: (_res: any) => {
        const emp_code = _res.data.emp_code;
        this.jobDetails.get('employee_id')?.patchValue(emp_code);
      },
      error: (_err: any) => {
        console.error('Error loading employees:', _err);
      }
    });
  }

  getEmployeeDetails() {
    const payload = {
      employee_uuid: this.id
    }
    this._httpClient.post(`${API_ENDPOINTS.employee.get_employee_details}`, payload).pipe(takeUntil(this.destroy$)).subscribe({
      next: (res: any) => {
        const employee = res?.data;
        if (!employee) return;
        this.loadDesignations(employee.job_details?.department_id || '');
        this.personalDetails.patchValue({
          firstName: employee.personal_details?.firstName || '',
          lastName: employee.personal_details?.lastName || '',
          email: employee.personal_details?.email || '',
          phone: employee.personal_details?.phone || '',
          dob: employee.personal_details?.dob
            ? new Date(employee.personal_details.dob)
            : null,
          gender: employee.personal_details?.gender || 'male',
          address: employee.personal_details?.address || '',
          maritalStatus: employee.personal_details?.maritalStatus || '',
          nationality: employee.personal_details?.nationality || ''
        });

        this.jobDetails.patchValue({
          // designation_id: employee.job_details?.designation_id || '',
          department_id: employee.job_details?.department_id || '',
          joiningDate: employee.job_details?.joiningDate ? new Date(employee.job_details.joiningDate) : null,
          workEmail: employee.job_details?.workEmail || '',
          reported_to: employee.job_details?.reported_to || '',
          work_location: employee.job_details?.work_location || '',
          workMode: employee.job_details?.workMode || '',
          role_id: employee.job_details?.role_id || '',
          probationStartDate: employee.job_details?.probationStartDate ? new Date(employee.job_details.probationStartDate) : null,
          probationEndDate: employee.job_details?.probationEndDate ? new Date(employee.job_details.probationEndDate) : null,
          probationStatus: employee.job_details?.probationStatus || '',
          probationNotes: employee.job_details?.probationNotes || '',
          employee_id: employee.job_details?.employee_id || '',
          employmentType: employee.job_details?.employmentType || '',
          shift: employee.job_details?.shift_id || ''
        });

        this.emergencyContactDetails.patchValue({
          contactName: employee.emergency_contact?.contactName || '',
          relation: employee.emergency_contact?.relation || '',
          phone: employee.emergency_contact?.phone || ''
        });

        this.loadDesignations(employee.job_details?.department_id || '');
        this.previewUrl.set(employee.personal_details.profileImage ? `${environment.apiUrl}/common/get_image/${employee.personal_details.profileImage}` :
          `https://ui-avatars.com/api/?name=${encodeURIComponent(`${employee.personal_details?.firstName || 'Emp'}`)}&background=random`,)

        this.jobDetails.get('designation_id')?.patchValue(employee.job_details?.designation_id || '');
      },
      error: (err) => {
        console.error('Error fetching employees:', err);
      }
    })
  }

  handleBack() {
    this._location.back();
  }

}

const dummydata = {
  "personal_details": {
    "firstName": "Koushik",
    "lastName": "Petluri",
    "email": "koushik@gmail.com",
    "phone": "9000000001",
    "dob": "1998-06-15",
    "gender": "male",
    "address": "Madhapur, Hyderabad, Telangana, India",
    "maritalStatus": "Single",
    "nationality": "Indian"
  },

  "job_details": {
    "joiningDate": "2026-02-01",
    "workEmail": "koushik@assettl.com",
    "work_location": "Hyderabad Office",
    "probationStartDate": "2026-02-01",
    "probationEndDate": "2026-05-01",
    "probationNotes": "Initial probation period",
    "employmentType": "FULL_TIME"
  },

  "emergency_contact": {
    "contactName": "Karthik",
    "phone": "9000000002"
  }
}

